name: DiscordIntegration
version: ${project.version}
main: dev.oakleycord.discordintegration.DiscordIntegration
author: OakleyCord
api-version: 1.19
description: §6§n§lAllows for players in Discord and Minecraft to chat with each other! Along with some other features!
commands:
  discord:
    description: §6§n§lAllows for players in Discord and Minecraft to chat with each other! Along with some other features!
    aliases: [di]
    usage: /discord
    permission: discordintegration.command.discord
    permission-message: §cYou do not have permission to use this command!